# **Carga de Datos**

In [1]:
# Modulos Requeridos
import numpy as np
import pandas as pd
import seaborn as sns

### Cargar datos desde modulo

In [2]:
vuelos = sns.load_dataset('flights')
vuelos

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

### Cargar datos desde archivo xlsx

In [3]:
ruta_archivoXLSX = 'datos.xlsx'
tabla = pd.read_excel(ruta_archivoXLSX)
tabla

   Sexo  Peso  Talla  Edad
0     M   126    167    18
1     M   120    151    27
2     M   155    148    23
3     F   117    167    28
4     M   144    166    22
5     F   105    174    20
6     F   151    147    33
7     F   120    175    31
8     M   106    162    32
9     F   102    169    23
10    M   125    156    35
11    F   104    166    26
12    M   118    142    26
13    F   153    180    29
14    F   166    161    32
15    F   148    166    27
16    M   123    149    28
17    M   145    168    29
18    M   127    174    34
19    F   133    161    22
20    F   125    171    35
21    F   126    150    27
22    F   143    140    35
23    F   130    145    26
24    M   110    150    23
25    F   122    177    21
26    M   161    179    18
27    F   131    182    30
28    M   117    156    23
29    F   155    169    28
30    F   144    182    31
31    M   134    146    26
32    M   113    172    31
33    M   170    177    20
34    M   156    142    25
35    M   109    147    27
36    M   143    141    26
37    M   124    172    26
38    F   152    148    19
39    F   164    184    32

### Cargar datos desde archivo csv

In [15]:
ruta_archivoCSV = 'planilla.csv'
planilla = pd.read_csv(ruta_archivoCSV)
planilla.set_index('codigo', inplace=True)
planilla

                   nombre  sueldo_base  bonificacion fecha_contratacion
codigo
1              Juan Pérez      5539.18       1199.81         2013-02-15
2               Ana Gómez      4122.55       1440.78         2014-09-25
3             Carlos Díaz      6357.85       1044.95         2015-06-19
4          Lucía Martínez      3367.74        839.27         2013-11-08
5          Pedro González      5798.63        858.55         2014-12-05
6             Marta López      5846.47        866.33         2015-01-10
7            Raúl Sánchez      4640.12        766.22         2013-03-23
8              Laura Ruiz      6221.32       1050.18         2012-08-14
9       Alberto Fernández      4675.93        926.45         2015-03-02
10            Sara García      7111.95       1337.10         2014-06-28
11             José Pérez      5179.42       1144.45         2014-02-12
12         Rocío Martínez      5760.84        988.32         2013-04-17
13           David Torres      4127.91       1181.19         2012-07-30
14        María Fernández      4833.92       1318.99         2014-10-01
15      José Luis Sánchez      7269.51        988.12         2015-07-23
16           Carmen Gómez      5470.27       1135.35         2014-11-16
17         Pedro González      6124.14       1072.72         2012-10-07
18            Esther Ruiz      6608.39       1327.82         2013-08-30
19          Antonio López      6816.92       1121.66         2012-06-04
20       Silvia Rodríguez      3802.44       1475.29         2014-02-01
21          Eduardo Pérez      6064.90       1172.74         2013-05-12
22            Sofía López      6189.52       1283.79         2012-11-17
23           Iván Sánchez      3282.73        595.23         2013-12-10
24        Patricia Torres      6145.59       1385.94         2015-06-11
25          Felipe Martín      5747.58       1067.13         2012-05-19
26            Elena Gómez      4793.61       1098.09         2015-11-24
27             Tomás Ruiz      7276.97       1244.25         2013-01-09
28              Ana Gómez      3307.42        951.79         2014-03-13
29            Carlos Díaz      5338.66        916.73         2015-02-20
30         Lucía Martínez      6443.77        827.47         2014-08-22

In [16]:
planilla.dtypes

nombre                 object
sueldo_base           float64
bonificacion          float64
fecha_contratacion     object
dtype: object

In [17]:
planilla['fecha_contratacion'] = pd.to_datetime(planilla['fecha_contratacion'])
planilla

                   nombre  sueldo_base  bonificacion fecha_contratacion
codigo
1              Juan Pérez      5539.18       1199.81         2013-02-15
2               Ana Gómez      4122.55       1440.78         2014-09-25
3             Carlos Díaz      6357.85       1044.95         2015-06-19
4          Lucía Martínez      3367.74        839.27         2013-11-08
5          Pedro González      5798.63        858.55         2014-12-05
6             Marta López      5846.47        866.33         2015-01-10
7            Raúl Sánchez      4640.12        766.22         2013-03-23
8              Laura Ruiz      6221.32       1050.18         2012-08-14
9       Alberto Fernández      4675.93        926.45         2015-03-02
10            Sara García      7111.95       1337.10         2014-06-28
11             José Pérez      5179.42       1144.45         2014-02-12
12         Rocío Martínez      5760.84        988.32         2013-04-17
13           David Torres      4127.91       1181.19         2012-07-30
14        María Fernández      4833.92       1318.99         2014-10-01
15      José Luis Sánchez      7269.51        988.12         2015-07-23
16           Carmen Gómez      5470.27       1135.35         2014-11-16
17         Pedro González      6124.14       1072.72         2012-10-07
18            Esther Ruiz      6608.39       1327.82         2013-08-30
19          Antonio López      6816.92       1121.66         2012-06-04
20       Silvia Rodríguez      3802.44       1475.29         2014-02-01
21          Eduardo Pérez      6064.90       1172.74         2013-05-12
22            Sofía López      6189.52       1283.79         2012-11-17
23           Iván Sánchez      3282.73        595.23         2013-12-10
24        Patricia Torres      6145.59       1385.94         2015-06-11
25          Felipe Martín      5747.58       1067.13         2012-05-19
26            Elena Gómez      4793.61       1098.09         2015-11-24
27             Tomás Ruiz      7276.97       1244.25         2013-01-09
28              Ana Gómez      3307.42        951.79         2014-03-13
29            Carlos Díaz      5338.66        916.73         2015-02-20
30         Lucía Martínez      6443.77        827.47         2014-08-22

In [18]:
planilla.dtypes

nombre                        object
sueldo_base                  float64
bonificacion                 float64
fecha_contratacion    datetime64[ns]
dtype: object

### Cargar Datos desde Yahoo

In [8]:
import yfinance as yf

In [9]:
ticker_apple = 'AAPL'
start_date = '2026-01-01'
end_date = '2026-01-19'
df_apple = yf.download(ticker_apple, start=start_date, end=end_date)

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AAPL']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

In [10]:
df_apple

Empty DataFrame
Columns: [(Adj Close, AAPL), (Close, AAPL), (High, AAPL), (Low, AAPL), (Open, AAPL), (Volume, AAPL)]
Index: []

### Acceso a GoogleDrive

In [19]:
# Enlace
# https://drive.google.com/file/d/1yGjTQBG7gGWeJ90m6ExV1OKx4i1aZz1D/view?usp=sharing
idFile = '1yGjTQBG7gGWeJ90m6ExV1OKx4i1aZz1D'
ruta = f'https://drive.google.com/uc?export=download&id={idFile}'
archivoGoogle = pd.read_csv(ruta)
archivoGoogle

,Date,Open,High,Low,Close,Adj Close,Volume
0,2020-11-02,109.110001,110.680000,107.320000,108.769997,107.780052,122866900
1,2020-11-03,109.660004,111.489998,108.730003,110.440002,109.434868,107624400
2,2020-11-04,114.139999,115.589996,112.349998,114.949997,113.903816,138235500
3,2020-11-05,117.949997,119.620003,116.870003,119.029999,117.946686,126387100
4,2020-11-06,118.320000,119.199997,116.129997,118.690002,117.812691,114457900
...,...,...,...,...,...,...,...
315,2022-02-02,174.750000,175.880005,173.330002,175.839996,175.616257,84914300
316,2022-02-03,174.479996,176.240005,172.119995,172.899994,172.679993,89418100
317,2022-02-04,171.679993,174.100006,170.679993,172.389999,172.389999,82391400
318,2022-02-07,172.860001,173.949997,170.949997,171.660004,171.660004,77251200
319,2022-02-08,171.729996,175.350006,171.429993,174.830002,174.830002,74706900

In [20]:
rutaGit = 'https://raw.githubusercontent.com/abemen/datasets/main/antropometricas.csv' 
antropo = pd.read_csv(rutaGit)
antropo

   Sexo  Peso  Talla  Edad
0     M   126    167    18
1     F   120    151    27
2     F   155    148    23
3     F   117    167    28
4     M   144    166    22
5     F   105    174    20
6     F   151    147    33
7     F   120    175    31
8     M   106    162    32
9     F   102    169    23
10    M   125    156    35
11    F   104    166    26
12    M   118    142    26
13    F   153    180    29
14    F   166    161    32
15    F   148    166    27
16    M   123    149    28
17    F   145    168    29
18    M   127    174    34
19    F   133    161    22
20    F   125    171    35
21    F   126    150    27
22    F   143    140    35
23    F   130    145    26
24    M   110    150    23
25    F   122    177    21
26    M   161    179    18
27    F   131    182    30
28    M   117    156    23
29    F   155    169    28
30    F   144    182    31
31    M   134    146    26
32    M   113    172    31
33    M   170    177    20
34    M   156    142    25
35    M   109    147    27
36    M   143    141    26
37    M   124    172    26
38    F   152    148    19
39    F   164    184    32

In [ ]:
# Para extraer lo que esta en el portapapeles:
# otros = pd.read_clipboard()   Si es csv se debe de colocar dentro de parentesis: read_clipboard(sep=',')
otros = pd.read_excel('otro.xlsx')
otros

,Date,Open,High,Low,Close,Adj Close,Volume
0,2020-11-02,109.110001,110.680000,107.320000,108.769997,107.780052,122866900
1,2020-11-03,109.660004,111.489998,108.730003,110.440002,109.434868,107624400
2,2020-11-04,114.139999,115.589996,112.349998,114.949997,113.903816,138235500
3,2020-11-05,117.949997,119.620003,116.870003,119.029999,117.946686,126387100
4,2020-11-06,118.320000,119.199997,116.129997,118.690002,117.812691,114457900
5,2020-11-09,120.500000,121.989998,116.050003,116.320000,115.460197,154515300
6,2020-11-10,115.550003,117.589996,114.129997,115.970001,115.112785,138023400
7,2020-11-11,117.190002,119.629997,116.440002,119.489998,118.606773,112295000
8,2020-11-12,119.620003,120.529999,118.570000,119.209999,118.328850,103162300

In [ ]:
otros.to_excel('otro.xlsx', index=False)  # Para dejar indice: Se quita index=False y para quitar cualquier columna (nombre de columna)=False

### Tablas cruzadas

In [27]:
contingencia = pd.crosstab(tabla['Edad'], tabla['Sexo'])
contingencia

Sexo  F  M
Edad
18    0  2
19    1  0
20    1  1
21    1  0
22    1  1
23    1  3
25    0  1
26    2  4
27    2  2
28    2  1
29    1  1
30    1  0
31    2  1
32    2  1
33    1  0
34    0  1
35    2  1

In [29]:
n = len(tabla)
intervalos = pd.cut(tabla['Edad'], bins=5)
intervalos

0     (17.983, 21.4]
1       (24.8, 28.2]
2       (21.4, 24.8]
3       (24.8, 28.2]
4       (21.4, 24.8]
5     (17.983, 21.4]
6       (31.6, 35.0]
7       (28.2, 31.6]
8       (31.6, 35.0]
9       (21.4, 24.8]
10      (31.6, 35.0]
11      (24.8, 28.2]
12      (24.8, 28.2]
13      (28.2, 31.6]
14      (31.6, 35.0]
15      (24.8, 28.2]
16      (24.8, 28.2]
17      (28.2, 31.6]
18      (31.6, 35.0]
19      (21.4, 24.8]
20      (31.6, 35.0]
21      (24.8, 28.2]
22      (31.6, 35.0]
23      (24.8, 28.2]
24      (21.4, 24.8]
25    (17.983, 21.4]
26    (17.983, 21.4]
27      (28.2, 31.6]
28      (21.4, 24.8]
29      (24.8, 28.2]
30      (28.2, 31.6]
31      (24.8, 28.2]
32      (28.2, 31.6]
33    (17.983, 21.4]
34      (24.8, 28.2]
35      (24.8, 28.2]
36      (24.8, 28.2]
37      (24.8, 28.2]
38    (17.983, 21.4]
39      (31.6, 35.0]
Name: Edad, dtype: category
Categories (5, interval[float64, right]): [(17.983, 21.4] < (21.4, 24.8] < (24.8, 28.2] < (28.2, 31.6] < (31.6, 35.0]]

In [31]:
frecuencias = pd.crosstab(index=intervalos, columns='f')
frecuencias

col_0            f
Edad
(17.983, 21.4]   6
(21.4, 24.8]     6
(24.8, 28.2]    14
(28.2, 31.6]     6
(31.6, 35.0]     8

In [33]:
frecuencias['fa'] = frecuencias['f'].cumsum()
frecuencias['fr'] = frecuencias['f'] / n
frecuencias['fra'] = frecuencias['fr'].cumsum()
frecuencias['%'] = frecuencias['fr']*100
frecuencias['%a'] = frecuencias['fra'] * 100
frecuencias

col_0            f  fa    fr   fra     %     %a
Edad
(17.983, 21.4]   6   6  0.15  0.15  15.0   15.0
(21.4, 24.8]     6  12  0.15  0.30  15.0   30.0
(24.8, 28.2]    14  26  0.35  0.65  35.0   65.0
(28.2, 31.6]     6  32  0.15  0.80  15.0   80.0
(31.6, 35.0]     8  40  0.20  1.00  20.0  100.0

In [37]:
frecuencias['Xm'] = frecuencias.index.categories.mid
frecuencias['f.Xm'] = frecuencias['f'] * frecuencias['Xm']
frecuencias

col_0            f  fa    fr   fra     %     %a       Xm     f.Xm
Edad
(17.983, 21.4]   6   6  0.15  0.15  15.0   15.0  19.6915  118.149
(21.4, 24.8]     6  12  0.15  0.30  15.0   30.0  23.1000  138.600
(24.8, 28.2]    14  26  0.35  0.65  35.0   65.0  26.5000  371.000
(28.2, 31.6]     6  32  0.15  0.80  15.0   80.0  29.9000  179.400
(31.6, 35.0]     8  40  0.20  1.00  20.0  100.0  33.3000  266.400

In [38]:
print(frecuencias['f.Xm'].sum() / n)  # Media

26.838725