# Web Scrapping

_Requerido:_

- Modulo: beautifulSoup
- pip install bs4

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO
import camelot
import matplotlib.pyplot as plt

In [ ]:
url = 'https://es.wikipedia.org/wiki/Organizaci%C3%B3n_territorial_de_Guatemala'
head = {'User-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

In [ ]:
response = requests.get(url, headers=head)

In [ ]:
print(f'Status Code: {response.status_code}')

Status Code: 200

In [ ]:
soup = BeautifulSoup(response.text, 'html.parser')

In [ ]:
tables = soup.find('table', {'class':'wikitable'})

In [ ]:
tables = pd.read_html(StringIO(str(tables)))
tables

[                                                    0  \
 0                          Departamentos de Guatemala
 1   Zacapa Chiquimula Sacatepéquez San Marcos Reta...
 2                                        Departamento
 3                                        Alta Verapaz
 4                                        Baja Verapaz
 5                                       Chimaltenango
 6                                          Chiquimula
 7                                         El Progreso
 8                                           Escuintla
 9                                           Guatemala
 10                                      Huehuetenango
 11                                             Izabal
 12                                             Jalapa
 13                                            Jutiapa
 14                                              Petén
 15                                     Quetzaltenango
 16                                             Quiché
 17                                         Retalhuleu
 18                                       Sacatepéquez
 19                                         San Marcos
 20                                         Santa Rosa
 21                                             Sololá
 22                                      Suchitepéquez
 23                                        Totonicapán
 24                                             Zacapa

                                                     1  \
 0                          Departamentos de Guatemala
 1   Zacapa Chiquimula Sacatepéquez San Marcos Reta...
 2                                            Cabecera
 3                                               Cobán
 4                                              Salamá
 5                                       Chimaltenango
 6                                          Chiquimula
 7                                          Guastatoya
 8                                           Escuintla
 9                                 Ciudad de Guatemala
 10                                      Huehuetenango
 11                                     Puerto Barrios
 12                                             Jalapa
 13                                            Jutiapa
 14                                             Flores
 15                                     Quetzaltenango
 16                              Santa Cruz del Quiché
 17                                         Retalhuleu
 18                                  Antigua Guatemala
 19                                         San Marcos
 20                                            Cuilapa
 21                                             Sololá
 22                                        Mazatenango
 23                                        Totonicapán
 24                                             Zacapa

                                                     2  \
 0                          Departamentos de Guatemala
 1   Zacapa Chiquimula Sacatepéquez San Marcos Reta...
 2                                    Superficie (km²)
 3                                               8 686
 4                                               3 124
 5                                               1 979
 6                                               2 376
 7                                               1 922
 8                                               4 384
 9                                               2 126
 10                                              7 400
 11                                              9 038
 12                                              2 063
 13                                              3 216
 14                                             35 854
 15                                              1 953
 16                                              8 378
 17                                              1 856
 18                                                465
 19                                              3 791
 20                                              2 955
 21                                              1 061
 22                                              2 510
 23                                              1 061
 24                                              2 690

                                                     3
 0                          Departamentos de Guatemala
 1   Zacapa Chiquimula Sacatepéquez San Marcos Reta...
 2                                Población (hab.)[1]​
 3                                           1 112 781
 4                                             270 521
 5                                             666 938
 6                                             370 891
 7                                             158 092
 8                                             701 016
 9                                           2 541 581
 10                                          1 143 887
 11                                            413 399
 12                                            318 420
 13                                            436 076
 14                                            638 296
 15                                            789 358
 16                                            953 027
 17                                            304 168
 18                                            248 019
 19                                          1 019 719
 20                                            346 590
 21                                            437 145
 22                                            516 467
 23                                            476 369
 24                                            221 646  ,
       Departamento               Cabecera Superficie (km²)  \
 0     Alta Verapaz                  Cobán            8 686
 1     Baja Verapaz                 Salamá            3 124
 2    Chimaltenango          Chimaltenango            1 979
 3       Chiquimula             Chiquimula            2 376
 4      El Progreso             Guastatoya            1 922
 5        Escuintla              Escuintla            4 384
 6        Guatemala    Ciudad de Guatemala            2 126
 7    Huehuetenango          Huehuetenango            7 400
 8           Izabal         Puerto Barrios            9 038
 9           Jalapa                 Jalapa            2 063
 10         Jutiapa                Jutiapa            3 216
 11           Petén                 Flores           35 854
 12  Quetzaltenango         Quetzaltenango            1 953
 13          Quiché  Santa Cruz del Quiché            8 378
 14      Retalhuleu             Retalhuleu            1 856
 15    Sacatepéquez      Antigua Guatemala              465
 16      San Marcos             San Marcos            3 791
 17      Santa Rosa                Cuilapa            2 955
 18          Sololá                 Sololá            1 061
 19   Suchitepéquez            Mazatenango            2 510
 20     Totonicapán            Totonicapán            1 061
 21          Zacapa                 Zacapa            2 690

    Población (hab.)[1]​
 0             1 112 781
 1               270 521
 2               666 938
 3               370 891
 4               158 092
 5               701 016
 6             2 541 581
 7             1 143 887
 8               413 399
 9               318 420
 10              436 076
 11              638 296
 12              789 358
 13              953 027
 14              304 168
 15              248 019
 16            1 019 719
 17              346 590
 18              437 145
 19              516 467
 20              476 369
 21              221 646  ]

In [ ]:
tables[1]

,Departamento,Cabecera,Superficie (km²),Población (hab.)[1]​
0,Alta Verapaz,Cobán,8 686,1 112 781
1,Baja Verapaz,Salamá,3 124,270 521
2,Chimaltenango,Chimaltenango,1 979,666 938
3,Chiquimula,Chiquimula,2 376,370 891
4,El Progreso,Guastatoya,1 922,158 092
5,Escuintla,Escuintla,4 384,701 016
6,Guatemala,Ciudad de Guatemala,2 126,2 541 581
7,Huehuetenango,Huehuetenango,7 400,1 143 887
8,Izabal,Puerto Barrios,9 038,413 399
9,Jalapa,Jalapa,2 063,318 420
10,Jutiapa,Jutiapa,3 216,436 076
11,Petén,Flores,35 854,638 296
12,Quetzaltenango,Quetzaltenango,1 953,789 358
13,Quiché,Santa Cruz del Quiché,8 378,953 027
14,Retalhuleu,Retalhuleu,1 856,304 168
15,Sacatepéquez,Antigua Guatemala,465,248 019
16,San Marcos,San Marcos,3 791,1 019 719
17,Santa Rosa,Cuilapa,2 955,346 590
18,Sololá,Sololá,1 061,437 145
19,Suchitepéquez,Mazatenango,2 510,516 467
20,Totonicapán,Totonicapán,1 061,476 369
21,Zacapa,Zacapa,2 690,221 646

In [ ]:
departamento = tables[1]

In [ ]:
departamento.columns = ['Departamento', 'Cabecera', 'Superficie', 'Poblacion']
departamento

      Departamento               Cabecera Superficie  Poblacion
0     Alta Verapaz                  Cobán      8 686  1 112 781
1     Baja Verapaz                 Salamá      3 124    270 521
2    Chimaltenango          Chimaltenango      1 979    666 938
3       Chiquimula             Chiquimula      2 376    370 891
4      El Progreso             Guastatoya      1 922    158 092
5        Escuintla              Escuintla      4 384    701 016
6        Guatemala    Ciudad de Guatemala      2 126  2 541 581
7    Huehuetenango          Huehuetenango      7 400  1 143 887
8           Izabal         Puerto Barrios      9 038    413 399
9           Jalapa                 Jalapa      2 063    318 420
10         Jutiapa                Jutiapa      3 216    436 076
11           Petén                 Flores     35 854    638 296
12  Quetzaltenango         Quetzaltenango      1 953    789 358
13          Quiché  Santa Cruz del Quiché      8 378    953 027
14      Retalhuleu             Retalhuleu      1 856    304 168
15    Sacatepéquez      Antigua Guatemala        465    248 019
16      San Marcos             San Marcos      3 791  1 019 719
17      Santa Rosa                Cuilapa      2 955    346 590
18          Sololá                 Sololá      1 061    437 145
19   Suchitepéquez            Mazatenango      2 510    516 467
20     Totonicapán            Totonicapán      1 061    476 369
21          Zacapa                 Zacapa      2 690    221 646

In [ ]:
region = soup.find_all('table')[2]
region = pd.read_html(StringIO(str(region)))[0]
region

,Región,Departamentos que la conforman,Extensión (km2),Población,Ciudad Más Poblada
0,Suroccidente (Región VI),Quetzaltenango Retalhuleu San Marcos Sololá...,12232,4398222,Quetzaltenango
1,Metropolitana (Región I),Guatemala,2253,3573179,Ciudad de Guatemala
2,Noroccidente (Región VII),Huehuetenango Quiché,15778,2686692,Huehuetenango
3,Central (Región V),Chimaltenango Escuintla Sacatepéquez,6828,1991006,Escuintla
4,Verapaz (Región II),Alta Verapaz Baja Verapaz,11810,1790153,Cobán
5,Nororiente (Región III),Chiquimula El Progreso Izabal Zacapa,16026,1410262,Puerto Barrios
6,Suroriente (Región IV),Jalapa Jutiapa Santa Rosa,8234,1347255,Jalapa
7,Petén (Región VIII),Petén,35854,858256,Santa Elena de la Cruz

In [ ]:
segeplan = soup.find_all('table')[3]
segeplan = pd.read_html(StringIO(str(segeplan)))[0]
segeplan

,Región,Departamento(s),Municipios
0,Petén,Petén,Todos los municipios
1,Franja Transversal del Norte,Huehuetenango,"Jacaltenango, Santa Ana Huista, San Antonio Hu..."
2,Franja Transversal del Norte,Izabal,"Puerto Barrios, Morales, Los Amates, El Estor ..."
3,Franja Transversal del Norte,Alta Verapaz,"Cobán, San Pedro Carchá, Senahú, Lanquín, Caha..."
4,Franja Transversal del Norte,Quiché,"Ixcán, Uspantán y Chajul."
5,Región Oriente,Zacapa,Todos los municipios
6,Región Oriente,El Progreso,Todos los municipios
7,Región Oriente,Chiquimula,Todos los municipios
8,Región Oriente,Izabal,"Puerto Barrios, Morales y Los Amates."
9,Región Oriente,Jutiapa,"Agua Blanca, Santa Catarina Mita, Asunción Mit..."
10,Región Oriente,Jalapa,Todos los municipios
11,Región Oriente,Santa Rosa,"Santa Rosa de Lima, Nueva Santa Rosa, San Rafa..."
12,Litoral del Pacífico,Jutiapa,Moyuta y Pasaco.
13,Litoral del Pacífico,Santa Rosa,"Chiquimulilla, Guazacapán y Taxisco."
14,Litoral del Pacífico,Escuintla,"Iztapa, San José, La Gomera, Nueva Concepción,..."
15,Litoral del Pacífico,Suchitepéquez,"Cuyotenango, Santo Domingo Suchitepéquez, San ..."
16,Litoral del Pacífico,Retalhuleu,Todos los municipios
17,Litoral del Pacífico,San Marcos,"Ocós, Ayutla, Pajapita, Catarina y Malacatán."
18,Litoral del Pacífico,Quetzaltenango,"Coatepeque, Génova, Colomba y Flores Costa Cuca."

In [ ]:
subregion = soup.find_all('table')[4]
subregion = pd.read_html(StringIO(str(subregion)))[0]
subregion

,Subregión,Departamento(s),Municipios
0,Subregión Polochic,Alta Verapaz,"Tucurú, Panzós, Senahú, Tactic y Tamahú."
1,Subregión Polochic,Izabal,Livingston y El Estor.
2,Subregión Polochic,Baja Verapaz,Purulhá
3,Xalalá,Quiché,Ixcán y Uspantán.
4,Xalalá,Alta Verapaz,Cobán

In [ ]:
departamento['Superficie'] = departamento['Superficie'].apply(lambda x: int(x.replace('\xa0', '')))
departamento

      Departamento               Cabecera  Superficie  Poblacion
0     Alta Verapaz                  Cobán        8686  1 112 781
1     Baja Verapaz                 Salamá        3124    270 521
2    Chimaltenango          Chimaltenango        1979    666 938
3       Chiquimula             Chiquimula        2376    370 891
4      El Progreso             Guastatoya        1922    158 092
5        Escuintla              Escuintla        4384    701 016
6        Guatemala    Ciudad de Guatemala        2126  2 541 581
7    Huehuetenango          Huehuetenango        7400  1 143 887
8           Izabal         Puerto Barrios        9038    413 399
9           Jalapa                 Jalapa        2063    318 420
10         Jutiapa                Jutiapa        3216    436 076
11           Petén                 Flores       35854    638 296
12  Quetzaltenango         Quetzaltenango        1953    789 358
13          Quiché  Santa Cruz del Quiché        8378    953 027
14      Retalhuleu             Retalhuleu        1856    304 168
15    Sacatepéquez      Antigua Guatemala         465    248 019
16      San Marcos             San Marcos        3791  1 019 719
17      Santa Rosa                Cuilapa        2955    346 590
18          Sololá                 Sololá        1061    437 145
19   Suchitepéquez            Mazatenango        2510    516 467
20     Totonicapán            Totonicapán        1061    476 369
21          Zacapa                 Zacapa        2690    221 646